name: Update GitHub Pages data.json

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -V
          # no external deps needed; if you add any, install here

      - name: Export latest data.json
        run: |
          python export_to_pages.py

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          if ! git diff --quiet docs/data.json; then
            git add docs/data.json
            git commit -m "chore(pages): refresh data.json"
            git push
          else
            echo "No changes in docs/data.json"
          fi


